### ISSUE TITLE
No Longer Working in Firefox 46

### ISSUE THREAD

**Issue by drmike** [JBPhoenix/ff-hide-plugin-bar#3]
Greetings:

Appears to be no longer working in 46.0.1.

Wish I could tell you more.  If there's a setting or something I can check for you, please let me know.

Thanks

edit: And, yes, I made sure I was talking about the correct addon.  :)

**Comment by JBPhoenix** [comment]
Hi there,
Thanks for the bug report and sorry you're having issues.

Just created a fresh profile with FF 46.0.1, but it seems to be working okay on my end - I don't remember any issues when I was on v46 with my main profile either, but that **was** a while ago.

As I can't reproduce the issue I'm not sure where to start, but if you're willing I can think of a few things that might help narrow down the problem:

- Would you be able to provide a screenshot of what you see, please? I assume you're just getting the Allow/Block nag bar, but it helps to see! Github should let you attach a screenshot.
- Do you know when it stopped working for you? Had you just upgraded to Firefox 46.0.1?
- Could you check which version of Hide Plugin Bar you have installed, please? 0.2.1 is the latest.
- Is it just a specific plugin (flash?) that you are being seeing the nag bar for, or are there others too?

**Comment by drmike** [comment]
Greets:  Not trying to ignore you.  This is just my busy time of the year.  I'm wondering if for some reason I;m seeing the bar because my install of Flash is out of date.  I was going to update it and see if Firefox still kicks out the bar.  Thank you for your time.  -drmike

**Comment by JBPhoenix** [comment]
Thanks for getting back to me, and I understand!
If your flash is quite old and/or insecure, that'd make sense. 
Does the bar look like this?
![image](https://cloud.githubusercontent.com/assets/8071405/20681366/3d711c42-b59b-11e6-93d7-da8eec94bbb4.png)

There is a setting in the addon options to hide the nag bar when Firefox has marked the plugin as insecure/vulnerable, but by default it shows these warnings.

Please let me know if updating Flash or changing the addon option fixes it for you.

**Comment by drmike** [comment]
That appears to have been the issue.  For reference, using Firefox 46.0.1 and an older version of Flash.

Uninstalled flash, rebooted, installed flash v23, set it to Ask to Activate, restarted firefox just in case, and visited the test site located here:

https://www.adobe.com/software/flash/about/

Got the grey boxes to activate flash but no bar along the top this time.

Thank you for your time
